"""create v1 tables

Revision ID: 98185fe3b1ec
Revises:
Create Date: 2026-05-01 20:21:49.235584
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "98185fe3b1ec"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_verification_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("phone_number_hash", sa.String(length=128), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_request_id", sa.String(length=128), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("result_code", sa.String(length=64), nullable=True),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sms_verification_events")),
    )
    op.create_index(
        "ix_sms_events_created_at", "sms_verification_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_sms_events_phone_created",
        "sms_verification_events",
        ["phone_number_hash", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=False),
        sa.Column("phone_verified_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_login_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_users_phone_number")),
    )
    op.create_index("ix_users_status", "users", ["status"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_user_updated", "conversations", ["user_id", "updated_at"], unique=False
    )
    op.create_table(
        "daily_archives",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("archive_date", sa.DATE(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("meal_count", sa.Integer(), nullable=False),
        sa.Column("body_metric_count", sa.Integer(), nullable=False),
        sa.Column("calorie_total", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("protein_total_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("carbs_total_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("fat_total_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("completeness_score", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("last_calculated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_archives_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_archives")),
        sa.UniqueConstraint("user_id", "archive_date", name="uq_daily_archives_user_date"),
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_ip_hash", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint(
            "refresh_token_hash", name=op.f("uq_refresh_sessions_refresh_token_hash")
        ),
    )
    op.create_index(
        "ix_refresh_sessions_expires_at", "refresh_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_refresh_sessions_revoked_at", "refresh_sessions", ["revoked_at"], unique=False
    )
    op.create_index("ix_refresh_sessions_user_id", "refresh_sessions", ["user_id"], unique=False)
    op.create_table(
        "upload_files",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("storage_provider", sa.String(length=32), nullable=False),
        sa.Column("client_local_ref", sa.String(length=256), nullable=True),
        sa.Column("bucket", sa.String(length=128), nullable=True),
        sa.Column("object_key", sa.String(length=512), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("retention_policy", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("deleted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_upload_files_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_files")),
    )
    op.create_index("ix_upload_files_status", "upload_files", ["status"], unique=False)
    op.create_index(
        "ix_upload_files_user_created", "upload_files", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_memories",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("memory_type", sa.String(length=32), nullable=False),
        sa.Column("memory_key", sa.String(length=128), nullable=False),
        sa.Column("memory_value_json", mysql.JSON(), nullable=False),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_memories_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_memories")),
    )
    op.create_index(
        "ix_user_memories_user_type_key",
        "user_memories",
        ["user_id", "memory_type", "memory_key"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=True),
        sa.Column("sex", sa.String(length=32), nullable=True),
        sa.Column("height_cm", mysql.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("current_weight_kg", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("target_weight_kg", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("activity_level", sa.String(length=32), nullable=True),
        sa.Column("goal_type", sa.String(length=32), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name="uq_user_profiles_user_id"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content_json", mysql.JSON(), nullable=False),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_messages_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversation_messages_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_messages")),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "conversation_messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_messages_user_created", "conversation_messages", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "daily_summaries",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("archive_id", sa.String(length=40), nullable=True),
        sa.Column("summary_date", sa.DATE(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("suggestions_json", mysql.JSON(), nullable=False),
        sa.Column("model_provider", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("generation_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["daily_archives.id"],
            name=op.f("fk_daily_summaries_archive_id_daily_archives"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_daily_summaries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_summaries")),
        sa.UniqueConstraint("user_id", "summary_date", name="uq_daily_summaries_user_date"),
    )
    op.create_table(
        "agent_extractions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("message_id", sa.String(length=40), nullable=True),
        sa.Column("input_types_json", mysql.JSON(), nullable=False),
        sa.Column("intent", sa.String(length=64), nullable=False),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("raw_output_json", mysql.JSON(), nullable=True),
        sa.Column("warnings_json", mysql.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_agent_extractions_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["conversation_messages.id"],
            name=op.f("fk_agent_extractions_message_id_conversation_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_extractions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_extractions")),
    )
    op.create_index(
        "ix_agent_extractions_message", "agent_extractions", ["message_id"], unique=False
    )
    op.create_index(
        "ix_agent_extractions_user_created",
        "agent_extractions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("from_message_id", sa.String(length=40), nullable=False),
        sa.Column("to_message_id", sa.String(length=40), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("token_estimate", sa.Integer(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_summaries_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["from_message_id"],
            ["conversation_messages.id"],
            name=op.f("fk_conversation_summaries_from_message_id_conversation_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["to_message_id"],
            ["conversation_messages.id"],
            name=op.f("fk_conversation_summaries_to_message_id_conversation_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_conversation_summaries_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_summaries")),
    )
    op.create_index(
        "ix_conversation_summaries_conversation_created",
        "conversation_summaries",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "message_attachments",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("message_id", sa.String(length=40), nullable=False),
        sa.Column("file_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["upload_files.id"],
            name=op.f("fk_message_attachments_file_id_upload_files"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["conversation_messages.id"],
            name=op.f("fk_message_attachments_message_id_conversation_messages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_attachments")),
        sa.UniqueConstraint("message_id", "file_id", name="uq_message_attachments_message_file"),
    )
    op.create_table(
        "agent_pending_actions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=False),
        sa.Column("source_message_id", sa.String(length=40), nullable=False),
        sa.Column("extraction_id", sa.String(length=40), nullable=True),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("draft_payload_json", mysql.JSON(), nullable=False),
        sa.Column("warnings_json", mysql.JSON(), nullable=True),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("confirmed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("committed_record_type", sa.String(length=32), nullable=True),
        sa.Column("committed_record_id", sa.String(length=40), nullable=True),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_agent_pending_actions_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["agent_extractions.id"],
            name=op.f("fk_agent_pending_actions_extraction_id_agent_extractions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["conversation_messages.id"],
            name=op.f("fk_agent_pending_actions_source_message_id_conversation_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_pending_actions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_pending_actions")),
    )
    op.create_index(
        "ix_pending_actions_conversation_status",
        "agent_pending_actions",
        ["conversation_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_pending_actions_expires_at", "agent_pending_actions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_pending_actions_user_status",
        "agent_pending_actions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "body_metric_records",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("recorded_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("recorded_tz", sa.String(length=64), nullable=False),
        sa.Column("local_date", sa.DATE(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("weight_kg", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("body_fat_percentage", mysql.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("bmi", mysql.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("muscle_mass_kg", mysql.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("water_percentage", mysql.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("source_pending_action_id", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_pending_action_id"],
            ["agent_pending_actions.id"],
            name=op.f("fk_body_metric_records_source_pending_action_id_agent_pending_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_body_metric_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_body_metric_records")),
    )
    op.create_index(
        "ix_body_metrics_user_date", "body_metric_records", ["user_id", "local_date"], unique=False
    )
    op.create_index(
        "ix_body_metrics_user_recorded_at",
        "body_metric_records",
        ["user_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "meal_records",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("recorded_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("recorded_tz", sa.String(length=64), nullable=False),
        sa.Column("local_date", sa.DATE(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("meal_type", sa.String(length=32), nullable=False),
        sa.Column("total_calories", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("total_protein_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("total_carbs_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("total_fat_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("source_pending_action_id", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("deleted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_pending_action_id"],
            ["agent_pending_actions.id"],
            name=op.f("fk_meal_records_source_pending_action_id_agent_pending_actions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_meal_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_records")),
    )
    op.create_index(
        "ix_meal_records_user_date", "meal_records", ["user_id", "local_date"], unique=False
    )
    op.create_index(
        "ix_meal_records_user_recorded_at", "meal_records", ["user_id", "recorded_at"], unique=False
    )
    op.create_table(
        "meal_items",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("meal_record_id", sa.String(length=40), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("alias", sa.String(length=128), nullable=True),
        sa.Column("portion_text", sa.String(length=128), nullable=True),
        sa.Column("portion_grams", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("calories", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("protein_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("carbs_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("fat_g", mysql.DECIMAL(precision=8, scale=2), nullable=True),
        sa.Column("confidence", mysql.DECIMAL(precision=5, scale=4), nullable=True),
        sa.Column("user_corrected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_record_id"],
            ["meal_records.id"],
            name=op.f("fk_meal_items_meal_record_id_meal_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_items")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_items")
    op.drop_index("ix_meal_records_user_recorded_at", table_name="meal_records")
    op.drop_index("ix_meal_records_user_date", table_name="meal_records")
    op.drop_table("meal_records")
    op.drop_index("ix_body_metrics_user_recorded_at", table_name="body_metric_records")
    op.drop_index("ix_body_metrics_user_date", table_name="body_metric_records")
    op.drop_table("body_metric_records")
    op.drop_index("ix_pending_actions_user_status", table_name="agent_pending_actions")
    op.drop_index("ix_pending_actions_expires_at", table_name="agent_pending_actions")
    op.drop_index("ix_pending_actions_conversation_status", table_name="agent_pending_actions")
    op.drop_table("agent_pending_actions")
    op.drop_table("message_attachments")
    op.drop_index(
        "ix_conversation_summaries_conversation_created", table_name="conversation_summaries"
    )
    op.drop_table("conversation_summaries")
    op.drop_index("ix_agent_extractions_user_created", table_name="agent_extractions")
    op.drop_index("ix_agent_extractions_message", table_name="agent_extractions")
    op.drop_table("agent_extractions")
    op.drop_table("daily_summaries")
    op.drop_index("ix_messages_user_created", table_name="conversation_messages")
    op.drop_index("ix_messages_conversation_created", table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_table("user_profiles")
    op.drop_index("ix_user_memories_user_type_key", table_name="user_memories")
    op.drop_table("user_memories")
    op.drop_index("ix_upload_files_user_created", table_name="upload_files")
    op.drop_index("ix_upload_files_status", table_name="upload_files")
    op.drop_table("upload_files")
    op.drop_index("ix_refresh_sessions_user_id", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_revoked_at", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_expires_at", table_name="refresh_sessions")
    op.drop_table("refresh_sessions")
    op.drop_table("daily_archives")
    op.drop_index("ix_conversations_user_updated", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_sms_events_phone_created", table_name="sms_verification_events")
    op.drop_index("ix_sms_events_created_at", table_name="sms_verification_events")
    op.drop_table("sms_verification_events")
    # ### end Alembic commands ###
